name: Build Python Project

on:
  push:
    branches:
      - main  # Adjust the branch name as needed

jobs:
  build:
    runs-on: ubuntu-latest  # Use the latest available GitHub-hosted runner

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2  # Check out your repository code

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x  # Specify the Python version you need

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Replace with your requirements file

      - name: Build Project
        run: |
          # Replace this with the commands needed to build your project
          python build.py  # Example command

      - name: Save Build Output
        run: |
          # Redirect the build output to a log file
          python build.py > build.log 2>&1

      - name: Upload Build Log
        uses: actions/upload-artifact@v2
        with:
          name: build-log
          path: build.log
